config/routes.rb
Campusevents::Application.routes.draw do
  root 'events#index'

  resources :subscriptions

  resources :attendees

  resources :meetings

  resources :locations

  resources :sponsors

  resources :events

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  validates :name, :start_time, :end_time, presence: true
  validate :dates_are_reasonable
  belongs_to :location
  belongs_to :event

  def dates_are_reasonable
    errors.add(:start_time, 'must be before end time') if start_time >= end_time
  end

  def location_name
    location.nil? ? "TBD" : location.name
  end

  def event_name
    event.nil? ? "TBD" : event.name
  end
end

app/controllers/meetings_controller.rb
require 'date'
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    set_date
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render action: 'show', status: :created, location: @meeting }
      else
        format.html { render action: 'new' }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    set_date
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :description, :start_time, :end_time, :location_id, :event_id)
    end

    def set_date
      begin_date = Date.strptime(params[:meeting]['start_time'], '%m-%d-%Y')
      end_date = Date.strptime(params[:meeting]['end_time'], '%m-%d-%Y')

      params[:meeting]['start_time'] = ''
      params[:meeting]['end_time'] = ''
      params[:meeting]['start_time(1i)'] = begin_date.year.to_s
      params[:meeting]['start_time(2i)'] = begin_date.month.to_s
      params[:meeting]['start_time(3i)'] = begin_date.mday.to_s
      params[:meeting]['end_time(1i)'] = end_date.year.to_s
      params[:meeting]['end_time(2i)'] = end_date.month.to_s
      params[:meeting]['end_time(3i)'] = end_date.mday.to_s
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>
      <ul>
        <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="small-8 columns">
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="small-5 columns">
      <%= f.label :start_time %><br>
      <div class="row">
        <div class="small-5 columns">
          <%= f.text_field :start_time, class: 'datepicker', :value => @meeting.start_time.nil? ? Time.now.strftime("%m-%d-%Y") : @meeting.start_time.strftime("%m-%d-%Y") %>
        </div>
        <div class="small-7 columns">
          <%= f.time_select :start_time, ampm: true, minute_step: 15, default: round_to_15_minutes(Time.now) %>
        </div>
      </div>
      <div class="field">
        <%= f.label :event_id %><br />
        <%= f.collection_select :event_id, Event.all, :id, :name, {include_blank: "Choose an Event"} %>
      </div>
    </div>
    <div class="small-5 columns">
      <%= f.label :end_time %><br>
      <div class="row">
        <div class="small-5 columns">
          <%= f.text_field :end_time, class: 'datepicker', :value => @meeting.end_time.nil? ? Time.now.strftime("%m-%d-%Y") : @meeting.end_time.strftime("%m-%d-%Y") %>
        </div>
        <div class="small-7 columns">
          <%= f.time_select :end_time, ampm: true, minute_step: 15, default: round_to_15_minutes(Time.now) %>
        </div>
      </div>
      <div class="field">
        <%= f.label :location_id %><br />
        <%= f.collection_select :location_id, Location.all, :id, :name, {include_blank: "Select a Location"} %>
      </div>
    </div>
    <div class="small-2 columns"></div>
  </div>
  <div class="actions">
    <%= f.submit class: "button" %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render 'form' %>

<div class="edit-navigation">
  <%= link_to 'Show', @meeting %> |
  <%= link_to 'Back', meetings_path %>
</div>

app/views/meetings/index.html.erb
<h1>Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Event</th>
      <th>Location</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.name %></td>
        <td><%= meeting.description %></td>
        <td><%= meeting.start_time.strftime('%m-%d-%Y %I:%M%p') %></td>
        <td><%= meeting.end_time.strftime('%m-%d-%Y %I:%M%p') %></td>
        <td><%= meeting.event_name %></td>
        <td><%= meeting.location_name %></td>
        <td><%= link_to 'Show', meeting %><br>
            <%= link_to 'Edit', edit_meeting_path(meeting) %><br>
            <%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path, class: 'button' %>

app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= render 'form' %>

<div class='edit-navigation'>
  <%= link_to 'Back', meetings_path %>
</div>

app/views/meetings/show.html.erb
<% content_for(:sidebar) do %>
  <h1>Location</h1>
  <%= link_to @meeting.location.name, @meeting.location %>
<% end %>

<h1><%= @meeting.name %></h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @meeting.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>

<div class="navigation">
  <%= link_to 'Edit', edit_meeting_path(@meeting) %> |
  <%= link_to 'Back', meetings_path %>
</div>