config/routes.rb
Campusevents::Application.routes.draw do
  root 'events#index'

  resources :subscriptions

  resources :attendees

  resources :meetings

  resources :locations

  resources :sponsors

  resources :events

end

app/views/shared/_events_table.html.erb
<table class="large-sidebar">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start Date</th>
      <th>End Date</th>
    </tr>
  </thead>
  <tbody>
    <% events.each do |event| %>
      <tr>
        <td><%= link_to event.name, event %></td>
        <td><%= event.start_date.strftime('%m-%d-%Y') %></td>
        <td><%= event.end_date.strftime('%m-%d-%Y') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_footer.html.erb
<!-- BEGIN INDIANA UNIVERSITY FOOTER -->
<div id="footer" role="contentinfo">
  <div class="wrapper">
        <p class="tagline">What matters. Where it matters.</p>
        <p class="internal"><a href="#">Privacy Notice</a></p>
        <p class="copyright">
            <a href="http://www.iu.edu/" class="block-iu"><%= image_tag 'block-iu.png', height: '26', width: '22', alt: 'Block IU' %></a> 
            <span class="line-break">
                <a href="http://www.iu.edu/copyright/index.shtml">Copyright</a> &#169; 
                <%= Time.now.year %> 
            </span> 
            <span class="line-break">The Trustees of <a href="http://www.iu.edu/">Indiana University</a>,</span> 
            <span class="line-break"><a href="http://www.iu.edu/copyright/complaints.shtml">Copyright Complaints</a></span>
        </p>
    </div>
</div>
<!-- END INDIANA UNIVERSITY FOOTER -->

app/views/shared/_meetings_table.html.erb
<table class="large-sidebar">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Start Time</th>
      <th>End Time</th>
    </tr>
  </thead>
  <tbody>
    <% meetings.each do |meeting| %>
      <tr>
        <td><%= link_to meeting.name, meeting %></td>
        <td><%= meeting.location_name %></td>
        <td><%= meeting.start_time.strftime('%m-%d-%Y %I:%M%p') %></td>
        <td><%= meeting.end_time.strftime('%m-%d-%Y %I:%M%p') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_topbar.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">IUPUI Campus Events</a></h1>
    </li>
    <li class="toggle-topbar menu-icon">
      <a href="#">Menu</a>
    </li>
  </ul>
  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="has-dropdown not-click">
        <a href="/">Menu</a>
        <ul class="dropdown">
          <li><%= link_to 'Events', events_path %></li>
          <li><%= link_to 'Meetings', meetings_path %></li>
          <li><%= link_to 'Sponsors', sponsors_path %></li>
          <li><%= link_to 'Locations', locations_path %></li>
          <li><%= link_to 'Attendees', attendees_path %></li>
          <li><%= link_to 'Subscriptions', subscriptions_path %></li>
        </ul>
      </li>
    </ul> 
    <!-- Left Nav Section -->
    <ul class="left">
      
    </ul>
  </section>
</nav>