config/routes.rb
Campusevents::Application.routes.draw do
  root 'events#index'

  resources :subscriptions

  resources :attendees

  resources :meetings

  resources :locations

  resources :sponsors

  resources :events

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  validates :first_name, :last_name, :email, presence: true
  has_many :subscriptions
  has_many :events, through: :subscriptions
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: [:show, :edit, :update, :destroy]

  # GET /attendees
  # GET /attendees.json
  def index
    @attendees = Attendee.all
  end

  # GET /attendees/1
  # GET /attendees/1.json
  def show
  end

  # GET /attendees/new
  def new
    @attendee = Attendee.new
  end

  # GET /attendees/1/edit
  def edit
  end

  # POST /attendees
  # POST /attendees.json
  def create
    @attendee = Attendee.new(attendee_params)

    respond_to do |format|
      if @attendee.save
        format.html { redirect_to @attendee, notice: 'Attendee was successfully created.' }
        format.json { render action: 'show', status: :created, location: @attendee }
      else
        format.html { render action: 'new' }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendees/1
  # PATCH/PUT /attendees/1.json
  def update
    respond_to do |format|
      if @attendee.update(attendee_params)
        format.html { redirect_to @attendee, notice: 'Attendee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1
  # DELETE /attendees/1.json
  def destroy
    @attendee.destroy
    respond_to do |format|
      format.html { redirect_to attendees_url }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_attendee
      @attendee = Attendee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendee_params
      params.require(:attendee).permit(:first_name, :last_name, :email)
    end
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/attendees/_form.html.erb
<%= form_for(@attendee) do |f| %>
  <% if @attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
      <% @attendee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit class: 'button' %>
  </div>
<% end %>

app/views/attendees/edit.html.erb
<h1>Editing attendee</h1>

<%= render 'form' %>

<div class="edit-navigation">
  <%= link_to 'Show', @attendee %> |
  <%= link_to 'Back', attendees_path %>
</div>

app/views/attendees/index.html.erb
<h1>Attendees</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @attendees.each do |attendee| %>
      <tr>
        <td><%= attendee.first_name %></td>
        <td><%= attendee.last_name %></td>
        <td><%= attendee.email %></td>
        <td><%= link_to 'Show', attendee %><br>
          <%= link_to 'Edit', edit_attendee_path(attendee) %><br>
          <%= link_to 'Destroy', attendee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendee', new_attendee_path, class: 'button' %>

app/views/attendees/new.html.erb
<h1>New attendee</h1>

<%= render 'form' %>

<div class="edit-navigation">
  <%= link_to 'Back', attendees_path %>
</div>

app/views/attendees/show.html.erb
<h1>Attendee</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @attendee.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @attendee.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @attendee.email %>
</p>

<div class="navigation">
  <%= link_to 'Edit', edit_attendee_path(@attendee) %> |
  <%= link_to 'Back', attendees_path %>
</div>